# scripts/load_data.py
# Inserts records generated by generate_fake_data.py into data/erp.db.

import sqlite3
import os

BASE_DIR = os.path.dirname(os.path.abspath(__file__))
DB_PATH = os.path.join(BASE_DIR, "..", "data", "erp.db")

from generate_fake_data import generate_all                                                                                                                                                                         
data = generate_all()    

conn   = sqlite3.connect(DB_PATH)
cursor = conn.cursor()

# Wipe existing data before loading to prevent duplicates
print("Clearing existing data...")
for table in ["payments", "invoices", "shipments", "sales_order_items", "sales_orders", "inventory", "products", "warehouses", "customers"]:
    cursor.execute(f"DELETE FROM {table}")
conn.commit()
print("Tables cleared.")

#Customers table
print("Loading customers...")                                                                                                                                                                                       
rows = [(d["customer_id"], d["customer_name"], d["customer_email"],d["region"],d["industry"],d["created_date"]) for d in data["customers"]]                                                                                                                                     
cursor.executemany("INSERT INTO customers VALUES (?,?,?,?,?,?)", rows)         
print(f"  {len(rows)} rows inserted.")  

# Products
print("Loading products...")
rows = [(d["product_id"], d["sku"], d["product_name"], d["category"], d["unit_cost"], d["unit_price"], d["active_flag"]) for d in data["products"]]
cursor.executemany("INSERT INTO products VALUES (?,?,?,?,?,?,?)", rows)
print(f"  {len(rows)} rows inserted.")

# Warehouses
print("Loading warehouses...")
rows = [(d["warehouse_id"], d["warehouse_name"], d["city"], d["state"]) for d in data["warehouses"]]
cursor.executemany("INSERT INTO warehouses VALUES (?,?,?,?)", rows)
print(f"  {len(rows)} rows inserted.")

# Inventory
print("Loading inventory...")
rows = [(d["inventory_id"], d["warehouse_id"], d["product_id"], d["quantity_on_hand"], d["reorder_point"], d["last_updated"]) for d in data["inventory"]]
cursor.executemany("INSERT INTO inventory VALUES (?,?,?,?,?,?)", rows)
print(f"  {len(rows)} rows inserted.")

# Sales Orders
print("Loading sales orders...")
rows = [(d["order_id"], d["customer_id"], d["order_date"], d["order_status"], d["requested_ship_date"], d["actual_ship_date"], d["total_amount"]) for d in data["orders"]]
cursor.executemany("INSERT INTO sales_orders VALUES (?,?,?,?,?,?,?)", rows)
print(f"  {len(rows)} rows inserted.")

# Sales Order Items
print("Loading order items...")
rows = [(d["order_item_id"], d["order_id"], d["product_id"], d["quantity"], d["unit_price"], d["line_total"]) for d in data["order_items"]]
cursor.executemany("INSERT INTO sales_order_items VALUES (?,?,?,?,?,?)", rows)
print(f"  {len(rows)} rows inserted.")

# Shipments
print("Loading shipments...")
rows = [(d["shipment_id"], d["order_id"], d["warehouse_id"], d["shipment_date"], d["delivery_date"], d["shipment_status"]) for d in data["shipments"]]
cursor.executemany("INSERT INTO shipments VALUES (?,?,?,?,?,?)", rows)
print(f"  {len(rows)} rows inserted.")

# Invoices
print("Loading invoices...")
rows = [(d["invoice_id"], d["order_id"], d["invoice_date"], d["due_date"], d["invoice_amount"], d["invoice_status"]) for d in data["invoices"]]
cursor.executemany("INSERT INTO invoices VALUES (?,?,?,?,?,?)", rows)
print(f"  {len(rows)} rows inserted.")

# Payments
print("Loading payments...")
rows = [(d["payment_id"], d["invoice_id"], d["payment_date"], d["payment_amount"], d["payment_method"]) for d in data["payments"]]
cursor.executemany("INSERT INTO payments VALUES (?,?,?,?,?)", rows)
print(f"  {len(rows)} rows inserted.")

conn.commit()
conn.close()
print("\nAll data loaded successfully.")
